Adding JSDoc and decorate README
Apacheli/Whirlybird pull request #2
Opened 2020-10-14 18:26 UTC by JeanCarlosVR

Adding best description and best references in readme about links, and JSDoc in ShardClient.ts

2020-10-14 21:43 UTC, Apacheli requested changes

2020-10-14 21:43 UTC, Apacheli commented on lib/ShardClient.ts
> +   * @param data.channel_id Channel ID
Should be camelCase e.g. `channel_id` -> `channelID`

2020-10-14 21:43 UTC, Apacheli commented on lib/ShardClient.ts
> +   * Request members from a guild [REST]
Not actually a REST method (but I will have REST implemented soon)

2020-10-14 21:43 UTC, Apacheli commented on lib/ShardClient.ts
> +   * @param data Base
I prefer `@arg` over `@param`

2020-10-15 02:42 UTC, JeanCarlosVR reviewed
Solved

2020-10-15 05:12 UTC, merged